name: moe-cd
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=25.0
  - python=3.10.16
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - blis==1.2.0
      - catalogue==2.0.10
      - certifi==2025.1.31
      - click==8.1.8
      - cloudpathlib==0.20.0
      - confection==0.1.5
      - cymem==2.0.11
      - en-core-web-sm==3.8.0
      - fsspec==2025.2.0
      - idna==3.10
      - joblib==1.4.2
      - langcodes==3.5.0
      - language-data==1.3.0
      - marisa-trie==1.2.1
      - markupsafe==3.0.2
      - murmurhash==1.0.12
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==2.2.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==24.2
      - pillow==11.1.0
      - preshed==3.0.9
      - pydantic==2.10.6
      - pytz==2025.1
      - pyyaml==6.0.2
      - safetensors==0.5.2
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - sentence-transformers==3.4.1
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.1.0
      - spacy==3.8.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - thinc==8.3.4
      - threadpoolctl==3.5.0
      - tokenizers==0.21.0
      - torch==2.6.0
      - tqdm==4.67.1
      - transformers==4.48.3
      - triton==3.2.0
      - typer==0.15.1
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - wrapt==1.17.2
