name: moe-cd
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - comm=0.2.2
  - debugpy=1.8.12
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ipykernel=6.29.5
  - ipython=8.32.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libsodium=1.0.20
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.4.0
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=26.2.1
  - readline=8.2
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - accelerate==1.3.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - alembic==1.14.1
      - altair==5.5.0
      - amqp==5.3.1
      - async-timeout==5.0.1
      - automaton==3.2.0
      - autopage==0.5.2
      - bcrypt==4.2.1
      - blinker==1.9.0
      - blis==1.2.0
      - cachetools==5.5.1
      - catalogue==2.0.10
      - certifi==2025.1.31
      - cffi==1.17.1
      - click==8.1.8
      - cliff==4.8.0
      - cloudpathlib==0.20.0
      - cloudpickle==3.1.1
      - cmd2==2.5.11
      - coloredlogs==15.0.1
      - confection==0.1.5
      - contourpy==1.3.1
      - cppimport==22.8.2
      - cryptography==44.0.1
      - cupy-cuda12x==13.3.0
      - cycler==0.12.1
      - cymem==2.0.11
      - databricks-sdk==0.43.0
      - datasets==3.2.0
      - debtcollector==3.0.0
      - deprecated==1.2.18
      - diffusers==0.32.2
      - dill==0.3.8
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - dogpile-cache==1.3.4
      - eventlet==0.39.0
      - fastapi==0.115.8
      - fasteners==0.19
      - fastrlock==0.8.3
      - flask==3.1.0
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - futurist==3.0.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.38.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.1.1
      - gunicorn==23.0.0
      - h11==0.14.0
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==8.5.0
      - iso8601==2.1.0
      - itsdangerous==2.2.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - keystoneauth1==5.9.1
      - keystonemiddleware==10.8.0
      - kiwisolver==1.4.8
      - kombu==5.4.2
      - langcodes==3.5.0
      - language-data==1.3.0
      - lightning-utilities==0.12.0
      - logutils==0.3.5
      - magnum==19.0.0
      - mako==1.3.9
      - marisa-trie==1.2.1
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mlflow==2.20.1
      - mlflow-skinny==2.20.1
      - msgpack==1.1.0
      - multiprocess==0.70.16
      - murmurhash==1.0.12
      - narwhals==1.26.0
      - netaddr==1.3.0
      - networkx==3.4.2
      - ninja==1.11.1.3
      - nltk==3.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-modelopt==0.23.1
      - nvidia-modelopt-core==0.23.1
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - onnx==1.17.0
      - onnx-graphsurgeon==0.5.5
      - onnxconverter-common==1.14.0
      - onnxmltools==1.13.0
      - onnxruntime==1.20.1
      - onnxruntime-gpu==1.20.1
      - openstacksdk==4.3.0
      - opentelemetry-api==1.30.0
      - opentelemetry-sdk==1.30.0
      - opentelemetry-semantic-conventions==0.51b0
      - os-client-config==2.1.0
      - os-service-types==1.7.0
      - osc-lib==3.2.0
      - oslo-cache==3.10.0
      - oslo-concurrency==7.0.0
      - oslo-config==9.7.0
      - oslo-context==5.7.0
      - oslo-db==17.1.0
      - oslo-i18n==6.5.0
      - oslo-log==7.0.0
      - oslo-messaging==16.0.0
      - oslo-metrics==0.10.1
      - oslo-middleware==6.3.0
      - oslo-policy==4.5.0
      - oslo-reports==3.5.0
      - oslo-serialization==5.6.0
      - oslo-service==4.0.0
      - oslo-upgradecheck==2.4.0
      - oslo-utils==8.1.0
      - oslo-versionedobjects==3.5.0
      - paste==3.10.1
      - pastedeploy==3.1.0
      - pbr==6.1.1
      - pecan==1.5.1
      - peft==0.14.0
      - pillow==11.1.0
      - plotly==6.0.0
      - preshed==3.0.9
      - prettytable==3.14.0
      - prometheus-client==0.21.1
      - propcache==0.2.1
      - protobuf==3.20.2
      - pulp==2.9.0
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybind11==2.13.6
      - pycadf==4.0.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydeck==0.9.1
      - pydot==3.0.4
      - pyjwt==2.10.1
      - pyopenssl==25.0.0
      - pyparsing==3.2.1
      - pyperclip==1.9.0
      - python-barbicanclient==7.0.0
      - python-cinderclient==9.6.0
      - python-glanceclient==4.7.0
      - python-heatclient==4.1.0
      - python-keystoneclient==5.5.0
      - python-neutronclient==11.4.0
      - python-novaclient==18.8.0
      - python-octaviaclient==3.9.0
      - python-openstackclient==7.2.1
      - python-swiftclient==4.6.0
      - pytorch-lightning==2.5.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - repoze-lru==0.7
      - requestsexceptions==1.4.0
      - rfc3986==2.0.0
      - routes==2.5.1
      - rsa==4.9
      - safetensors==0.5.2
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - seaborn==0.13.2
      - sentence-transformers==3.4.1
      - sentry-sdk==2.20.0
      - setproctitle==1.3.4
      - shellingham==1.5.4
      - simplegeneric==0.8.1
      - smart-open==7.1.0
      - smmap==5.0.2
      - spacy==3.8.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.38
      - sqlparse==0.5.3
      - srsly==2.5.1
      - starlette==0.45.3
      - statsd==4.0.1
      - stevedore==5.4.0
      - streamlit==1.42.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - taskflow==5.10.0
      - tenacity==9.0.0
      - tensorrt==10.7.0.post1
      - tensorrt-cu12==10.7.0.post1
      - tensorrt-cu12-bindings==10.7.0.post1
      - tensorrt-cu12-libs==10.7.0.post1
      - testresources==2.0.1
      - testscenarios==0.5.0
      - testtools==2.7.2
      - thinc==8.3.4
      - threadpoolctl==3.5.0
      - tokenizers==0.21.0
      - torch==2.6.0
      - torch-tensorrt==2.6.0
      - torchmetrics==1.6.1
      - torchprofile==0.0.4
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.48.3
      - triton==3.2.0
      - typer==0.15.1
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - vine==5.1.0
      - wandb==0.19.6
      - warlock==2.0.1
      - wasabi==1.1.3
      - watchdog==6.0.0
      - weasel==0.4.1
      - webob==1.8.9
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - wsme==0.12.1
      - xxhash==3.5.0
      - yappi==1.6.10
      - yarl==1.18.3
